[package]
name = "ztron"
version = "0.1.0"
authors = ["andelf <andelf@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
bech32 = "0.7"
hex = "0.4"
sha2 = "0.9"

keys = { path = "../keys" }

# zcash_primitives = { git = "https://github.com/andelf/librustzcash", branch = "ztron" }
# zcash_proofs = { git = "https://github.com/andelf/librustzcash", branch = "ztron" }
# pairing = { git = "https://github.com/andelf/librustzcash", branch = "ztron" }
# ff = { git = "https://github.com/andelf/librustzcash", branch = "ztron" }
# bellman = { git = "https://github.com/andelf/librustzcash", branch = "ztron" }
# primitive-types = "0.7"

zcash_primitives = { path = "../../librustzcash" }
zcash_proofs = { path = "../../librustzcash" }
pairing = { path = "../../librustzcash" }
ff = { path = "../../librustzcash" }
bellman = { path = "../../librustzcash" }
