name: Rust

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - name: Install protobuf
              run: sudo apt-get install protobuf-compiler libprotobuf-dev
            - name: Build walletd
              run: cargo build -p walletd
            - name: Build wallet-cli
              run: cargo build -p wallet-cli
            - name: Run tests
              run: cargo test
