name: Rust

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - name: Install protobuf
              run: sudo apt-get install protobuf-compiler libprotobuf-dev
            - name: Build
              run: cargo build --all
            - name: Run tests
              run: cargo test --all
