name: Rust

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - name: Install protobuf
              run: sudo apt-get install protobuf-compiler libprotobuf-dev
            - name: Install RocksDB
              run: |
                sudo apt-get install libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev libzstd-dev
                git clone https://github.com/facebook/rocksdb.git
                cd rocksdb
                git checkout v6.7.3
                sudo make install-shared
            - name: Download ztron-params
              run: |
                ./scripts/download-ztron-params.sh
            - name: Run tests
              run: cargo test --workspace
