name: Rust

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Checkout submodules
              shell: bash
              run: |
                git submodule sync --recursive
                git submodule update --init --force --recursive --depth=1
            - name: Install protobuf
              run: sudo apt-get install protobuf-compiler
            - name: Build
              run: cargo build --all
            - name: Run tests
              run: cargo test --all
